### PR TITLE
add the goBack() method to the page object

### PR DESCRIPTION
**Pull request by luismesas**
### Proposed changes in this pull request

add the goBack() method to the page object

#### Checklist
* [x] New tests have been added
* [x] `npm test` passes successfully
* [ ] Documentation has been updated

@amir20 to review

### CODE REVIEW

**Comment by amir20** [comment]
Needs tests. @luismesas besides that looks good.

**Comment by luismesas** [comment]
test added

**Comment by amir20** [comment]
You are awesome. Merging.

**Comment by amir20** [comment]
Apparently I forgot to merge.

**Comment by amir20** [comment]
2.1.17 released.

**Pull request merged**
