### PR TITLE
Add custom PhantomJS path support by passing it in config object to phantom.create()

### PR DESCRIPTION
**Pull request by akkenoth**
### Proposed changes in this pull request

Added possibility of using custom PhantomJS path by adding 'config' object to Phantom c-tor (with 'phantomPath' property inside).
Added docs and tests.
Tested in production, works well even with older PhantomJS binaries (namely 1.9.8 from npm package phantomjs@1.9.20)

#### Checklist
* [x] New tests have been added
* [x] `npm test` passes successfully
* [ ] Documentation has been updated

@amir20 to review

### CODE REVIEW

**Comment by akkenoth** [comment]
Test npm tarball available here: https://github.com/greatcare/phantomjs-node/releases/tag/v2.1.11-4

**Comment by amir20** [comment]
Nice job. I don't see documentation updated though. Can you also update the README file so people know how to use the override?

**Comment by akkenoth** [comment]
Added docs to README.md, also included some notes on kill() and exit() (which now returns a promise - it can be ignored but in some cases we should wait for it to resolve).

As a sidenote, I observed that the child phantomjs process WILL be killed when main nodejs process receives SIGINT (e.g. by ctrl-c). I'm not 100% sure if it's always the case though.

**Comment by elias-winberg** [comment]
@akkenoth the `exit` promise will never be resolved, as the process will exit before the response is sent.

**Comment by akkenoth** [comment]
Right. The passing tests has misleaded me, I have tested it further and it does not resolve just as you have said.
The weird thing is that Jasmine accepts timeouts in afterAll hook, whereas MochaJS which I am used to does not (and it generally makes working with async code, especially promises, much more pleasurable).

Docs adjusted, I think it should be ready for merge now.

**Comment by amir20** [comment]
Looking good. Merging and releasing.

**Pull request merged**
