### PR TITLE
fix #551 Unexpected replacement characters

### LINKED ISSUE #551: Unexpected replacement characters
### Expected behavior

Page content is returned as utf-8 string w/o replacement characters ([wiki](https://en.wikipedia.org/wiki/Specials_%28Unicode_block%29)).
### Actual behavior

The replacement characters have appeared in random places of HTML code.
### Steps to reproduce the behavior
1. Open NodeJS console
2. Run the code:

``` javascript
var phantom = require("phantom");
function run(opts) {
    phantom.create(opts).then(function(proc) {
        proc.createPage().then(function(page) {
            page.open("http://varlamov.ru/1960870.html").then(function() {
                page.property('content').then(function (html) {
                    console.log(html.indexOf('\ufffd'));
                });
            });
        });
    });
}

run();
run();
run();
run(['--output-encoding=utf8']);
run(['--output-encoding=utf8']);
run(['--output-encoding=utf8']);
```
1. See different numbers not dependent from options
2. Open view-source:http://varlamov.ru/1960870.html in browser and see no replacement characters
### Environment
- OS: Ubuntu 14.04
- Node version (`node -v`): v6.2.2, v6.4.0
- package version: 2.1.21

### PR DESCRIPTION
**Pull request by weilao**
### Proposed changes in this pull request

fix #551

#### Checklist
* [ ] New tests have been added
* [ ] `npm test` passes successfully
* [ ] Documentation has been updated

@amir20 to review

### CODE REVIEW

**Comment by amir20** [comment]
Npm tests don't seem to pass

**Comment by amir20** [comment]
Ping @weilao

**Comment by weilao** [comment]
Sorry,but I can't pass the test even using the unmodified code.

**Comment by amir20** [comment]
Hmm. Not sure. Do you know what it is not passing? Travis has [master](https://travis-ci.org/amir20/phantomjs-node/builds/178106445) passing. I also tried running it locally and it works. 

I am sorry, but I can't merge until there is a green build. That's absolutely required.

**Comment by amir20** [comment]
I'll have to play with `split2` myself.

**Comment by amir20** [comment]
I created https://github.com/rvagg/through2/issues/77. Maybe related.

**Pull request closed without merging**
