### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package winston from 2.2.0 to 2.3.1
 Npm link :  https://www.npmjs.com/package/winston
 Repository link : https://github.com/winstonjs/winston/releases

### CODE REVIEW

**Comment by amir20** [comment]
This is not really needed as it is already starts with `^`. When I install locally, I already have latest version. `npm outdated` doesn't have it and `npm ls winston` -> `winston@2.3.1`.

Also other files like package-lock.json and yarn.lock need to be updated too for future reference.

**Comment by EsrefDurna** [comment]
if you want npm will update a higher version 
why don't you test it before npm distributes ? you want npm to install ^packageName but you don't want to test it with your module?

**Comment by EsrefDurna** [comment]
yes this is the irony of open source,
you are alright with other packages update them self and install whatever they distribute into your package,
but you also don't willing to test,

**Comment by amir20** [comment]
@EsrefDurna I don't understand what you are saying. But 2.3.1 is already installed. So I don't think there is anything to test. 

```

└─┬ phantom@4.0.4
  └── winston@2.3.1 
```

**Comment by amir20** [comment]
Also with node 8 it uses the lock file. https://github.com/amir20/phantomjs-node/blob/master/package-lock.json#L4529

**Pull request closed without merging**
