### PR TITLE
exit() now returns promise

### PR DESCRIPTION
**Pull request by mubraska**
### Proposed changes in this pull request

Exitting now returns Promise in order to be able to wait properly.

@amir20 to review

### CODE REVIEW

**Comment by diegoperini** [comment]
This should be the default behavior.

**Comment by amir20** [comment]
Please add a test and fix the Travis build.

**Comment by amir20** [comment]
ping @diegoperini . See comments above.

**Comment by amir20** [comment]
Looks like you forgot give type to `Promise`

**Pull request closed without merging**
